# Projet tutoré

## Import

In [3]:
import pandas as pd # Afin de gérer les tableaux 
import numpy as np

In [4]:
data = pd.read_csv('run40_reactions.tsv',sep="\t", header=0) #Ouvrir le tableau 
data.head

/home/paulinehg/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (48,49,50,51,52,53,54,55,56,62,63,73,93,95,96,97,98,99,100,101,102,103,109,120,140) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


<bound method NDFrame.head of                           reaction  Galdieria_sulphuraria  Neurospora_crassa  \
0                   HOMOCYSMET-RXN                      1                  1   
1                         RXN-1827                      1                  0   
2                        RXN-19009                      1                  0   
3                        RXN0-1141                      1                  1   
4                        RXN-19141                      1                  0   
...                            ...                    ...                ...   
4882                  2.6.1.50-RXN                      0                  0   
4883                      RXN-8581                      0                  0   
4884        UDP-NACMUR-ALA-LIG-RXN                      0                  0   
4885                      RXN-9909                      0                  0   
4886  BENZYL-ALC-DEHYDROGENASE-RXN                      0                  0   

      Ect

In [5]:
#On ne garde que les algues brunes du tableau 
brunes = data[['Thalassiosira_pseudonana', 'Fragilariopsis_cylindrus', 'Phaeodactylum_tricornutum', 'Nannochloropsis_gaditana','Ectocarpus_siliculosus','Ectocarpus_crouaniorum','Ectocarpus_subulatus','Ectocarpus_fasciculatus','Scytosiphon_lomentaria','Porterinema_fluviatile','Nemacystus_decipiens','Cladosiphon_okamuranus','Laminarionema_elsbetiae','Saccharina_japonica','Undaria_pinnatifida']]
brunes.head

<bound method NDFrame.head of       Thalassiosira_pseudonana  Fragilariopsis_cylindrus  \
0                            1                         1   
1                            0                         0   
2                            1                         1   
3                            1                         1   
4                            1                         1   
...                        ...                       ...   
4882                         0                         0   
4883                         0                         0   
4884                         0                         0   
4885                         0                         0   
4886                         0                         0   

      Phaeodactylum_tricornutum  Nannochloropsis_gaditana  \
0                             1                         1   
1                             0                         0   
2                             1                         1   
3    

In [4]:
#Ne garder que les lignes où il y a au moins quatorze 1 (soit toutes les algues possèdent la réaction sauf une)
brunes_np = brunes.to_numpy() #pour manipulier le tableau plus facilement
reaction = []
for i in range(len(brunes_np)):
    count = 0
    for j in range(15):
        if brunes_np[i,j] == 1:
            count = count + 1
    if count>= 14:
            reaction.append(i)
print(len(reaction))

2189


In [5]:
print(brunes_np[1,:])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [6]:
#On crée un nouveau tableau qui ne garde que ces lignes
brunes_al = np.zeros((len(reaction),15))
for i in range(len(reaction)):
    nb = reaction[i]
    brunes_al[i,:] = brunes_np[nb,:]
print(brunes_al[2039,:])
print(brunes_al[2038,:])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
#On repère que Laminarionema_elsbetiae correspond à la 13e colonne, (d'identation [:,12])
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss = []
for i in range(len(brunes_al)):
    if brunes_al[i,12] == 0.:
        loss.append(i)
print(len(loss)) #nombre de réactions perdues au total
print(loss)
print(brunes_al[8,:])

121
[8, 22, 34, 51, 86, 116, 130, 151, 168, 174, 214, 248, 254, 266, 361, 402, 413, 415, 418, 443, 463, 470, 478, 483, 505, 540, 544, 555, 572, 629, 633, 639, 700, 711, 723, 757, 769, 786, 789, 792, 839, 847, 852, 874, 886, 893, 931, 941, 955, 959, 964, 976, 1029, 1032, 1046, 1054, 1060, 1065, 1090, 1122, 1132, 1134, 1136, 1155, 1181, 1186, 1191, 1193, 1204, 1223, 1236, 1247, 1274, 1278, 1308, 1310, 1315, 1353, 1365, 1371, 1389, 1432, 1459, 1469, 1480, 1493, 1535, 1559, 1585, 1593, 1671, 1679, 1699, 1707, 1731, 1814, 1818, 1832, 1861, 1875, 1883, 1897, 1908, 1915, 1941, 1952, 1987, 1990, 1998, 2001, 2005, 2015, 2026, 2036, 2051, 2072, 2075, 2082, 2115, 2170, 2184]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]


In [8]:
#On récupère maintenant le numéro de la réaction initiale perdue
reac_loss = []
for i in range(len(loss)):
    reac_loss.append(reaction[loss[i]])
print(reac_loss)

[15, 31, 50, 70, 122, 161, 182, 210, 235, 244, 291, 340, 348, 367, 485, 538, 552, 556, 561, 593, 626, 636, 645, 650, 683, 733, 738, 754, 779, 856, 864, 872, 955, 974, 989, 1042, 1059, 1080, 1084, 1088, 1151, 1161, 1167, 1197, 1213, 1221, 1278, 1290, 1309, 1314, 1322, 1340, 1411, 1414, 1434, 1447, 1455, 1461, 1493, 1537, 1551, 1553, 1556, 1583, 1617, 1622, 1628, 1630, 1645, 1671, 1685, 1697, 1737, 1741, 1778, 1780, 1786, 1842, 1863, 1869, 1895, 1949, 1993, 2013, 2028, 2045, 2097, 2127, 2158, 2169, 2284, 2297, 2326, 2343, 2374, 2485, 2489, 2507, 2547, 2564, 2581, 2635, 2678, 2719, 2836, 2870, 2974, 2986, 3007, 3020, 3026, 3062, 3101, 3151, 3221, 3282, 3293, 3312, 3376, 3473, 3507]


In [9]:
#On peut ainsi récupérer leur nom avec la colonne reaction de data 
loss_name = []
for i in range(len(reac_loss)):
    loss_name.append(data.loc[reac_loss[i],"reaction"])

print(loss_name)
print(len(loss_name))

['MRNA-GUANINE-N7--METHYLTRANSFERASE-RXN', 'RXN-14481', 'RXN-20531', 'RETINOL-DEHYDROGENASE-RXN', 'OROTPDECARB-RXN', 'SPHINGOSINE-N-ACYLTRANSFERASE-RXN', 'DTDPDEHYDRHAMEPIM-RXN', 'RXN0-6491', '3.4.21.26-RXN', 'RXN-17472', 'RXN-11757', 'RXN0-302', 'OROPRIBTRANS-RXN', 'RXN-20407', 'RXN-11136', 'GLUTAMATE-SYNTHASE-FERREDOXIN-RXN', 'RXN-7800', 'RXN-12878', 'RXN-15843', 'ATPPHOSPHORIBOSYLTRANS-RXN', '3-HYDROXYBUTYRYL-COA-DEHYDROGENASE-RXN', 'DTDPDEHYRHAMREDUCT-RXN', 'METHIONINE-GAMMA-LYASE-RXN', 'RXN-9229', 'UROGENDECARBOX-RXN', '2-OCTAPRENYL-6-OHPHENOL-METHY-RXN', 'RXN-9951', 'DIOHBUTANONEPSYN-RXN', 'RXN-14480', 'RXN3O-102', 'RXN0-5063', 'RXN-12581', 'RXN-20404', '2.7.1.134-RXN', 'RXN-20401', 'ORNITHINE-GLU-AMINOTRANSFERASE-RXN', 'RXN-9279', 'ADENPRIBOSYLTRAN-RXN', 'RXN-19915', 'RXN-9287', 'GTP-CYCLOHYDRO-II-RXN', 'RXN-7792', 'RXN-9280', 'CITSYN-RXN', 'DIHYDROOROTATE-DEHYDROGENASE-RXN', 'RXN-17753', 'RXN-14515', 'RXN-9282', 'RXN-7790', 'RXN-9281', 'RXN-20368', '2.8.1.6-RXN', 'RXN-8642', 'T

In [10]:
pip install pandas-ods-reader  #pour gérer qutre type de tableau 

     |████████████████████████████████| 125 kB 2.0 MB/s eta 0:00:01
  Created wheel for ezodf: filename=ezodf-0.3.2-py2.py3-none-any.whl size=49002 sha256=463a3c3414463638a023989bfc30cafc0dcf86cad17c7225dc3f6ce478c18238
  Stored in directory: /home/paulinehg/.cache/pip/wheels/d0/0e/c2/1af349f0c9e110ed08133a3d579f402f3ec1c031eac80bc084
Successfully built ezodf
Note: you may need to restart the kernel to use updated packages.


In [11]:
from pandas_ods_reader import read_ods
df = read_ods('Lelsb_losses.ods') # Lecture du tableau provenant de l'analyse faite à la main 
df.head

<bound method NDFrame.head of                Identifiant Metacyc  \
0            PHOSACETYLTRANS-RXN     
1                   2.3.1.75-RXN     
2                   4.4.1.14-RXN     
3                      RXN-11371     
4                      RXN-12199     
..                             ...   
93                    3.2.1.14-RXN   
94          3-ISOPROPYLMALISOM-RXN   
95                       RXN-20516   
96  D-ALANINE-AMINOTRANSFERASE-RXN   
97                       RXN-11634   

                                         Nom réaction  \
0                       Phosphate acetyltransferase     
1                                Wax ester synthase     
2        1-aminocyclopropane-1-carboxylate synthase     
3     2-(3-amino-3-carboxypropyl)histidine synthase     
4          nucleoside triphosphate phosphohydrolase     
..                                                ...   
93                                               None   
94                                               None   


In [13]:
f_name = [] #récupération des noms des réactions 
for i in range(98):
    f_name.append(df.loc[i,"Identifiant Metacyc"])
print(f_name)

['PHOSACETYLTRANS-RXN  ', '2.3.1.75-RXN  ', '4.4.1.14-RXN  ', 'RXN-11371  ', 'RXN-12199  ', 'GART-RXN  ', 'RXN0-5098  ', 'EXOPOLYPHOSPHATASE-RXN  ', 'RXN0-5101  ', 'GLYCEROL-KIN-RXN  ', 'RXN-18702  ', '1.5.1.20-RXN  ', 'GDP-MANNOSE-6-DEHYDROGENASE-RXN  ', 'RXN-20436  ', 'RXN-4210  ', 'RXN66-323 ', 'RXN-20557  ', 'RXN-20519  ', 'METHYLCROTONYL-COA-CARBOXYLASE-RXN  ', 'RXN-7421  ', 'RXN-17882  ', 'GLYOXYLATE-OXIDASE-RXN  ', 'RXN-5468  ', 'RXN-7667 ', 'GLYCOGENIN-GLUCOSYLTRANSFERASE-RXN  ', 'RXN-8642 ', 'CARDIOLIPSYN-RXN ', 'RXN1G01-65 ', '2KETO-3METHYLVALERATE-RXN ', 'DIOHBUTANONEPSYN-RXN ', '3.2.1.58-RXN ', '2.1.1.79-RXN ', 'RXN1A0-6303 ', 'GTP-CYCLOHYDRO-II-RXN', '1.1.1.188-RXN', 'RXN3DJ-11417', 'GMP-SYN-GLUT-RXN', 'RETINOL-DEHYDROGENASE-RXN', 'TRANS-RXN0-277', 'RXN-13719', 'RXN-8141', 'KETOISOCAPROATE-RXN', '2.1.1.5-RXN', 'RNA-LIGASE-ATP-RXN', 'RXN0-6491', 'DIPHOSPHOMEVALONTE-DECARBOXYLASE-RXN', 'DTDPDEHYRHAMREDUCT-RXN', '2.7.7.14-RXN', 'RXN-17927', 'RXN-13760', 'DTDPDEHYDRHAMEPIM-RXN

In [14]:
nb = 0
for i in loss_name: # comparaison des deux listes 
    if i in f_name:
        print(i, 'est aussi dans la première liste')
        nb = nb + 1
print(nb, 'réactions sont dans les deux listes')

MRNA-GUANINE-N7--METHYLTRANSFERASE-RXN est aussi dans la première liste
RETINOL-DEHYDROGENASE-RXN est aussi dans la première liste
DTDPDEHYDRHAMEPIM-RXN est aussi dans la première liste
RXN0-6491 est aussi dans la première liste
3.4.21.26-RXN est aussi dans la première liste
DTDPDEHYRHAMREDUCT-RXN est aussi dans la première liste
RXN-9951 est aussi dans la première liste
RXN-12581 est aussi dans la première liste
GTP-CYCLOHYDRO-II-RXN est aussi dans la première liste
DIHYDROOROTATE-DEHYDROGENASE-RXN est aussi dans la première liste
RXN-17753 est aussi dans la première liste
GMP-SYN-NH3-RXN est aussi dans la première liste
AIRS-RXN est aussi dans la première liste
ISOCITDEH-RXN est aussi dans la première liste
TRYPTOPHAN--TRNA-LIGASE-RXN est aussi dans la première liste
RXN-11634 est aussi dans la première liste
RXN0-6554 est aussi dans la première liste
GMP-SYN-GLUT-RXN est aussi dans la première liste
RXN-8991 est aussi dans la première liste
3-ISOPROPYLMALISOM-RXN est aussi dans la p

## Identifier les pertes de gènes chez les autres algues brunes.

On reprend le tableau qui commend les réactions qui sont présentes chez toutes les algues brunes, sauf une : `brunes_al`.

Pour *Thalassiosira_pseudonana* d'identation [:,0].

In [15]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Tp = []
for i in range(len(brunes_al)):
    if brunes_al[i,0] == 0.:
        loss_Tp.append(i)
print(len(loss_Tp))
print(loss_Tp)
print(brunes_al[184,:])

64
[184, 186, 189, 231, 297, 328, 400, 409, 450, 521, 568, 612, 631, 686, 726, 727, 741, 744, 745, 748, 780, 793, 795, 828, 840, 853, 896, 944, 1031, 1053, 1076, 1168, 1261, 1329, 1355, 1416, 1594, 1680, 1710, 1766, 1783, 1828, 1834, 1835, 1900, 1905, 1909, 1913, 1951, 1955, 1969, 1979, 1980, 1986, 2009, 2010, 2013, 2027, 2029, 2038, 2046, 2064, 2068, 2144]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Pour *Fragilariopsis_cylindrus* d'identation [:,1].

In [16]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Fc = []
for i in range(len(brunes_al)):
    if brunes_al[i,1] == 0.:
        loss_Fc.append(i)
print(len(loss_Fc))
print(loss_Fc)
print(brunes_al[13,:])

22
[13, 47, 312, 399, 416, 448, 456, 461, 677, 820, 1063, 1161, 1309, 1411, 1672, 1901, 1946, 1950, 1962, 2019, 2175, 2188]
[1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Pour *Phaeodactylum_tricornutum*, d'identation `[:,2]`.

In [17]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Pt = []
for i in range(len(brunes_al)):
    if brunes_al[i,2] == 0.:
        loss_Pt.append(i)
print(len(loss_Pt))
print(loss_Pt)
print(brunes_al[53,:])

25
[53, 183, 213, 467, 524, 622, 738, 926, 993, 1035, 1069, 1070, 1146, 1262, 1645, 1693, 1896, 1994, 2012, 2016, 2042, 2062, 2124, 2126, 2145]
[1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Pour *Nannochloropsis_gaditana*, d'identation `[:,3]`.

In [18]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Ng = []
for i in range(len(brunes_al)):
    if brunes_al[i,3] == 0.:
        loss_Ng.append(i)
print(len(loss_Ng))
print(loss_Ng)
print(brunes_al[42,:])

100
[42, 77, 150, 156, 197, 230, 262, 270, 287, 293, 327, 329, 339, 364, 369, 433, 445, 466, 514, 557, 614, 662, 690, 747, 752, 798, 800, 816, 825, 913, 918, 925, 967, 1128, 1140, 1149, 1152, 1182, 1187, 1214, 1217, 1226, 1241, 1242, 1271, 1280, 1294, 1317, 1330, 1361, 1363, 1397, 1398, 1478, 1488, 1514, 1606, 1650, 1666, 1724, 1727, 1741, 1756, 1770, 1793, 1803, 1806, 1885, 1899, 1912, 1922, 1923, 1931, 1934, 1936, 1938, 1940, 1945, 1948, 1961, 1968, 1972, 1976, 1983, 1988, 2006, 2028, 2030, 2052, 2054, 2065, 2069, 2073, 2081, 2105, 2122, 2132, 2140, 2152, 2163]
[1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Pour *Ectocarpus_siliculosus*, d'identation `[:,4]`.

In [19]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Esi = []
for i in range(len(brunes_al)):
    if brunes_al[i,4] == 0.:
        loss_Esi.append(i)
print(len(loss_Esi))
print(loss_Esi)
print(brunes_al[1333,:])

3
[1333, 1422, 1801]
[1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Pour *Ectocarpus_crouaniorum*, d'identation `[:,5]`.

In [20]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Ec = []
for i in range(len(brunes_al)):
    if brunes_al[i,5] == 0.:
        loss_Ec.append(i)
print(len(loss_Ec))
print(loss_Ec)
print(brunes_al[40,:])

8
[40, 932, 1049, 1064, 1382, 1460, 1616, 1821]
[1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Pour *Ectocarpus_subulatus*, d'identation `[:,6]`.

In [21]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Esu = []
for i in range(len(brunes_al)):
    if brunes_al[i,6] == 0.:
        loss_Esu.append(i)
print(len(loss_Esu))
print(loss_Esu)
print(brunes_al[274,:])

21
[274, 291, 311, 523, 556, 604, 624, 628, 644, 718, 761, 1028, 1107, 1301, 1465, 1475, 1498, 1537, 1714, 1734, 2180]
[1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]


Pour *Ectocarpus_fasciculatus*, d'identation `[:,7]`.

In [22]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Ef = []
for i in range(len(brunes_al)):
    if brunes_al[i,7] == 0.:
        loss_Ef.append(i)
print(len(loss_Ef))
print(loss_Ef)
print(brunes_al[1039,:])

5
[1039, 1148, 1632, 1949, 1975]
[1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]


Pour *Scytosiphon_lomentaria*, d'identation `[:,8]`. 

In [23]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Sl = []
for i in range(len(brunes_al)):
    if brunes_al[i,8] == 0.:
        loss_Sl.append(i)
print(len(loss_Sl))
print(loss_Sl)
print(brunes_al[1579,:])

1
[1579]
[1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]


Pour *Porterinema_fluviatile*, d'identation `[:,9]`.

In [24]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Pf = []
for i in range(len(brunes_al)):
    if brunes_al[i,9] == 0.:
        loss_Pf.append(i)
print(len(loss_Pf))
print(loss_Pf)

0
[]


Pour *Nemacystus_decipiens*, d'identation `[:,10]`. 

In [25]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Nd = []
for i in range(len(brunes_al)):
    if brunes_al[i,10] == 0.:
        loss_Nd.append(i)
print(len(loss_Nd))
print(loss_Nd)
print(brunes_al[68,:])

20
[68, 131, 310, 455, 778, 915, 968, 1001, 1034, 1401, 1467, 1495, 1561, 1849, 1862, 1864, 2107, 2113, 2162, 2164]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]


Pour *Cladosiphon_okamuranus*, d'identation `[:,11]`.

In [26]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Co = []
for i in range(len(brunes_al)):
    if brunes_al[i,11] == 0.:
        loss_Co.append(i)
print(len(loss_Co))
print(loss_Co)
print(brunes_al[99,:])

18
[99, 106, 181, 255, 268, 276, 733, 1088, 1144, 1339, 1384, 1623, 1655, 1668, 1686, 1757, 2114, 2116]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]


Pour *Saccharina_japonica*, d'identation `[:,13]`.

In [27]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Sj = []
for i in range(len(brunes_al)):
    if brunes_al[i,13] == 0.:
        loss_Sj.append(i)
print(len(loss_Sj))
print(loss_Sj)
print(brunes_al[447,:])

8
[447, 895, 1072, 1091, 1349, 1426, 1886, 2123]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]


Pour *Undaria_pinnatifida*, d'identation `[:,14]`.

In [28]:
#On cherche donc pour quelle réaction, c'est elle qui n'a pas la réaction
loss_Up = []
for i in range(len(brunes_al)):
    if brunes_al[i,14] == 0.:
        loss_Up.append(i)
print(len(loss_Up))
print(loss_Up)
print(brunes_al[191,:])

6
[191, 551, 775, 803, 1137, 1210]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]


## Retrouver le nom des gènes chez les autres algues brunes qui on été perdus par Laminarionema

In [32]:
#On reprend le tableau reactions et on récupère seulement les colonnes avec le nom des gènes
brunes_reac = data[['Thalassiosira_pseudonana_genes_assoc (sep=;)', 'Fragilariopsis_cylindrus_genes_assoc (sep=;)', 'Phaeodactylum_tricornutum_genes_assoc (sep=;)', 'Nannochloropsis_gaditana_genes_assoc (sep=;)','Ectocarpus_siliculosus_genes_assoc (sep=;)','Ectocarpus_crouaniorum_genes_assoc (sep=;)','Ectocarpus_subulatus_genes_assoc (sep=;)','Ectocarpus_fasciculatus_genes_assoc (sep=;)','Scytosiphon_lomentaria_genes_assoc (sep=;)','Porterinema_fluviatile_genes_assoc (sep=;)','Nemacystus_decipiens_genes_assoc (sep=;)','Cladosiphon_okamuranus_genes_assoc (sep=;)','Laminarionema_elsbetiae_genes_assoc (sep=;)','Saccharina_japonica_genes_assoc (sep=;)','Undaria_pinnatifida_genes_assoc (sep=;)']]
brunes_reac.head

<bound method NDFrame.head of            Thalassiosira_pseudonana_genes_assoc (sep=;)  \
0                                        THAPSDRAFT_693   
1                                                   NaN   
2                                       THAPSDRAFT_5510   
3     THAPS_263147;THAPSDRAFT_31673;THAPSDRAFT_26469...   
4     THAPSDRAFT_24832;THAPSDRAFT_261310;THAPSDRAFT_...   
...                                                 ...   
4882                                                NaN   
4883                                                NaN   
4884                                                NaN   
4885                                                NaN   
4886                                                NaN   

           Fragilariopsis_cylindrus_genes_assoc (sep=;)  \
0                   FRACYDRAFT_207237;FRACYDRAFT_228154   
1                                                   NaN   
2     FRACYDRAFT_291658;FRACYDRAFT_261203;FRACYDRAFT...   
3     FRACYDRAFT_270353;F

In [36]:
# Ensuite, on récupère l'indice des 24 réactions perdues 
loss24 = []
for i in loss_name:
    if i in f_name:
        loss24.append(i)
print(loss24)
reaction = data.loc[:,"reaction"]
print(reaction)

loss24_nb = []
for i in loss24:
    for j in range(len(reaction)):
        if reaction[j] == i:
            loss24_nb.append(j)
        

['MRNA-GUANINE-N7--METHYLTRANSFERASE-RXN', 'RETINOL-DEHYDROGENASE-RXN', 'DTDPDEHYDRHAMEPIM-RXN', 'RXN0-6491', '3.4.21.26-RXN', 'DTDPDEHYRHAMREDUCT-RXN', 'RXN-9951', 'RXN-12581', 'GTP-CYCLOHYDRO-II-RXN', 'DIHYDROOROTATE-DEHYDROGENASE-RXN', 'RXN-17753', 'GMP-SYN-NH3-RXN', 'AIRS-RXN', 'ISOCITDEH-RXN', 'TRYPTOPHAN--TRNA-LIGASE-RXN', 'RXN-11634', 'RXN0-6554', 'GMP-SYN-GLUT-RXN', 'RXN-8991', '3-ISOPROPYLMALISOM-RXN', '2.7.7.14-RXN', '3.2.1.14-RXN', 'RXN-17879', 'NAPHTHOATE-SYN-RXN']
0                     HOMOCYSMET-RXN
1                           RXN-1827
2                          RXN-19009
3                          RXN0-1141
4                          RXN-19141
                    ...             
4882                    2.6.1.50-RXN
4883                        RXN-8581
4884          UDP-NACMUR-ALA-LIG-RXN
4885                        RXN-9909
4886    BENZYL-ALC-DEHYDROGENASE-RXN
Name: reaction, Length: 4887, dtype: object


In [37]:
print(loss24_nb)
print(reaction[15])

[15, 70, 182, 210, 235, 636, 738, 872, 1151, 1213, 1221, 1556, 1645, 1697, 1786, 1863, 1895, 2169, 2374, 2507, 3062, 3151, 3312, 3473]
MRNA-GUANINE-N7--METHYLTRANSFERASE-RXN


Maintenant, on regarde pour chaque algue brune (autre que *Laminarionema*) à quel gène correspond chaque réaction.

Pour *Thalassiosira_pseudonana*.

In [38]:
for i in loss24_nb:
    print(reaction[i], ':', brunes_reac.loc[i,'Thalassiosira_pseudonana_genes_assoc (sep=;)'])

MRNA-GUANINE-N7--METHYLTRANSFERASE-RXN : THAPS_10979
RETINOL-DEHYDROGENASE-RXN : THAPSDRAFT_17956
DTDPDEHYDRHAMEPIM-RXN : THAPSDRAFT_40788
RXN0-6491 : THAPSDRAFT_264316;THAPSDRAFT_262575
3.4.21.26-RXN : THAPSDRAFT_7546
DTDPDEHYRHAMREDUCT-RXN : THAPSDRAFT_8901;THAPSDRAFT_4064;THAPSDRAFT_40788;THAPSDRAFT_4068
RXN-9951 : THAPSDRAFT_21640;THAPSDRAFT_1456
RXN-12581 : THAPSDRAFT_17956
GTP-CYCLOHYDRO-II-RXN : THAPSDRAFT_33619;THAPSDRAFT_268695;THAPSDRAFT_28100
DIHYDROOROTATE-DEHYDROGENASE-RXN : THAPSDRAFT_264316;THAPSDRAFT_262575
RXN-17753 : nan
GMP-SYN-NH3-RXN : THAPSDRAFT_40223
AIRS-RXN : THAPSDRAFT_20580
ISOCITDEH-RXN : THAPSDRAFT_21640;THAPSDRAFT_1456
TRYPTOPHAN--TRNA-LIGASE-RXN : THAPSDRAFT_3461;THAPSDRAFT_43160
RXN-11634 : THAPSDRAFT_28300
RXN0-6554 : THAPSDRAFT_264316;THAPSDRAFT_262575
GMP-SYN-GLUT-RXN : THAPSDRAFT_40223
RXN-8991 : THAPSDRAFT_42704
3-ISOPROPYLMALISOM-RXN : THAPSDRAFT_42704
2.7.7.14-RXN : THAPSDRAFT_42946;THAPSDRAFT_20823;THAPSDRAFT_35017
3.2.1.14-RXN : THAPSDRAFT_23700

In [39]:
#1221
print(brunes_reac.loc[1221,'Thalassiosira_pseudonana_genes_assoc (sep=;)'])
print(brunes.loc[1221,'Thalassiosira_pseudonana'])

nan
1


Pour *Fragilariopsis_cylindrus*.

In [40]:
for i in loss24_nb:
    print(reaction[i], ':',brunes_reac.loc[i,'Fragilariopsis_cylindrus_genes_assoc (sep=;)'])
print(brunes_reac.loc[1221,'Fragilariopsis_cylindrus_genes_assoc (sep=;)'])

MRNA-GUANINE-N7--METHYLTRANSFERASE-RXN : FRACYDRAFT_186017
RETINOL-DEHYDROGENASE-RXN : FRACYDRAFT_144249
DTDPDEHYDRHAMEPIM-RXN : FRACYDRAFT_191008
RXN0-6491 : FRACYDRAFT_182199;FRACYDRAFT_159735
3.4.21.26-RXN : FRACYDRAFT_206739;FRACYDRAFT_244058;FRACYDRAFT_174438
DTDPDEHYRHAMREDUCT-RXN : FRACYDRAFT_191008;FRACYDRAFT_160971
RXN-9951 : FRACYDRAFT_277597;FRACYDRAFT_168262
RXN-12581 : FRACYDRAFT_144249
GTP-CYCLOHYDRO-II-RXN : FRACYDRAFT_172456;FRACYDRAFT_207039
DIHYDROOROTATE-DEHYDROGENASE-RXN : FRACYDRAFT_182199;FRACYDRAFT_159735
RXN-17753 : nan
GMP-SYN-NH3-RXN : FRACYDRAFT_275358
AIRS-RXN : FRACYDRAFT_257579;FRACYDRAFT_209097
ISOCITDEH-RXN : FRACYDRAFT_168262;FRACYDRAFT_277597
TRYPTOPHAN--TRNA-LIGASE-RXN : FRACYDRAFT_268525;FRACYDRAFT_192001
RXN-11634 : FRACYDRAFT_188724
RXN0-6554 : FRACYDRAFT_182199;FRACYDRAFT_159735
GMP-SYN-GLUT-RXN : FRACYDRAFT_275358
RXN-8991 : FRACYDRAFT_223273
3-ISOPROPYLMALISOM-RXN : FRACYDRAFT_223273
2.7.7.14-RXN : FRACYDRAFT_205852;FRACYDRAFT_190693
3.2.1.14-RX

Pour *Phaeodactylum_tricornutum*.

In [41]:
for i in loss24_nb:
    print(reaction[i], ':',brunes_reac.loc[i,'Phaeodactylum_tricornutum_genes_assoc (sep=;)'])

MRNA-GUANINE-N7--METHYLTRANSFERASE-RXN : PHATRDRAFT_43071
RETINOL-DEHYDROGENASE-RXN : PHATRDRAFT_15297
DTDPDEHYDRHAMEPIM-RXN : PHATRDRAFT_23281
RXN0-6491 : PHATRDRAFT_48112;PHATRDRAFT_48900
3.4.21.26-RXN : PHATRDRAFT_46548
DTDPDEHYRHAMREDUCT-RXN : PHATRDRAFT_23281
RXN-9951 : PHATRDRAFT_45017;PHATRDRAFT_14762
RXN-12581 : PHATRDRAFT_15297
GTP-CYCLOHYDRO-II-RXN : PHATRDRAFT_6454;PHATRDRAFT_42619;PHATRDRAFT_10882
DIHYDROOROTATE-DEHYDROGENASE-RXN : PHATRDRAFT_48112;PHATRDRAFT_48900
RXN-17753 : nan
GMP-SYN-NH3-RXN : PHATRDRAFT_27735
AIRS-RXN : PHATRDRAFT_47067
ISOCITDEH-RXN : PHATRDRAFT_45017;PHATRDRAFT_14762
TRYPTOPHAN--TRNA-LIGASE-RXN : PHATRDRAFT_40901;PHATRDRAFT_15595
RXN-11634 : PHATRDRAFT_19122
RXN0-6554 : PHATRDRAFT_48112;PHATRDRAFT_48900
GMP-SYN-GLUT-RXN : PHATRDRAFT_27735
RXN-8991 : PHATRDRAFT_24772
3-ISOPROPYLMALISOM-RXN : PHATRDRAFT_24772
2.7.7.14-RXN : PHATRDRAFT_44584;PHATRDRAFT_40163
3.2.1.14-RXN : PHATRDRAFT_44884;PHATRDRAFT_50155
RXN-17879 : PHATRDRAFT_50507;PHATR_10391
NAPHT

Pour *Nannochloropsis_gaditana*.

In [42]:
for i in loss24_nb:
    print(brunes_reac.loc[i,'Nannochloropsis_gaditana_genes_assoc (sep=;)'])

Naga_100004g74;Naga_100001g88
Naga_100159g6;Naga_100008g96
Naga_100199g4
Naga_100144g11
Naga_100093g9
Naga_100012g46;Naga_100199g4;Naga_100014g19
Naga_100022g53
Naga_100159g6;Naga_100008g96
Naga_100071g6;Naga_100158g13;Naga_100250g5
Naga_100144g11
nan
Naga_101462g1
Naga_100004g33;Naga_100190g12;Naga_100169g16;Naga_100001g134
Naga_100022g53
Naga_100083g10;Naga_100041g13
Naga_100002g149
Naga_100144g11
Naga_101462g1
Naga_100877g4;Naga_100048g8
Naga_100877g4;Naga_100048g8
Naga_100049g31;Naga_100004g40
Naga_100210g10
Naga_100337g5
Naga_100074g14


In [43]:
for i in loss24_nb:
    print(i, ':',
         'Tp', '=', brunes_reac.loc[i,'Thalassiosira_pseudonana_genes_assoc (sep=;)'], '\n',
         'Fc', '=',brunes_reac.loc[i,'Fragilariopsis_cylindrus_genes_assoc (sep=;)'],'\n',
         'Pt', '=',brunes_reac.loc[i,'Phaeodactylum_tricornutum_genes_assoc (sep=;)'],'\n',
         'Ng', '=',brunes_reac.loc[i,'Nannochloropsis_gaditana_genes_assoc (sep=;)'],'\n',
         'Esi', '=',brunes_reac.loc[i,'Ectocarpus_siliculosus_genes_assoc (sep=;)'],'\n',
         'Ec', '=',brunes_reac.loc[i,'Ectocarpus_crouaniorum_genes_assoc (sep=;)'],'\n',
         'Esu', '=',brunes_reac.loc[i,'Ectocarpus_subulatus_genes_assoc (sep=;)'],'\n',
         'Ef', '=',brunes_reac.loc[i,'Ectocarpus_fasciculatus_genes_assoc (sep=;)'],'\n',
         'Sl', '=',brunes_reac.loc[i,'Scytosiphon_lomentaria_genes_assoc (sep=;)'],'\n',
         'Pf', '=',brunes_reac.loc[i,'Porterinema_fluviatile_genes_assoc (sep=;)'],'\n',
         'Nd', '=',brunes_reac.loc[i,'Nemacystus_decipiens_genes_assoc (sep=;)'],'\n',
         'Co', '=',brunes_reac.loc[i,'Cladosiphon_okamuranus_genes_assoc (sep=;)'],'\n',
         'Sj', '=',brunes_reac.loc[i,'Saccharina_japonica_genes_assoc (sep=;)'],'\n',
         'Up', '=',brunes_reac.loc[i,'Undaria_pinnatifida_genes_assoc (sep=;)'])

15 : Tp = THAPS_10979 
 Fc = FRACYDRAFT_186017 
 Pt = PHATRDRAFT_43071 
 Ng = Naga_100004g74;Naga_100001g88 
 Esi = E_siliculosus_16569 
 Ec = Ecrouaniorum_06620 
 Esu = EsuBft80_27 
 Ef = Efasciculatus_06433 
 Sl = Slomentaria_17517 
 Pf = Pfluviatile_06283 
 Nd = g16087 
 Co = C_okamuranus_15110;C_okamuranus_03802 
 Sj = SJ04718 
 Up = Undaria_15095;Undaria_34133;Undaria_10655;Undaria_37066
70 : Tp = THAPSDRAFT_17956 
 Fc = FRACYDRAFT_144249 
 Pt = PHATRDRAFT_15297 
 Ng = Naga_100159g6;Naga_100008g96 
 Esi = E_siliculosus_05605;E_siliculosus_05410;E_siliculosus_05793;E_siliculosus_14176 
 Ec = Ecrouaniorum_06211;Ecrouaniorum_09597;Ecrouaniorum_17064 
 Esu = EsuBft1405_8;EsuBft655_5;EsuBft1287_4;EsuBft153_6 
 Ef = Efasciculatus_01775;Efasciculatus_05943;Efasciculatus_03358;Efasciculatus_03360 
 Sl = Slomentaria_16704;Slomentaria_02147;Slomentaria_02146;Slomentaria_01984;Slomentaria_16705 
 Pf = Pfluviatile_02577;Pfluviatile_13362 
 Nd = g4869;g9047;g4870;g9046;g10715 
 Co = C_okamuran

In [44]:
print(reaction[3473])
print(reaction[1221])

NAPHTHOATE-SYN-RXN
RXN-17753
